// Code generated by MockGen. DO NOT EDIT.
// Source: internal/command/infraestructure/entrypoints/handlers/handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	domain "reservation-api/internal/command/core/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// SaveReservation mocks base method.
func (m *MockUseCase) SaveReservation(reservation domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveReservation", reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveReservation indicates an expected call of SaveReservation.
func (mr *MockUseCaseMockRecorder) SaveReservation(reservation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveReservation", reflect.TypeOf((*MockUseCase)(nil).SaveReservation), reservation)
}
